global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # Scrape do Elasticsearch Exporter
  - job_name: 'elasticsearch'
    metrics_path: /metrics
    static_configs:
      - targets: ['es-exporter:9114']

  # Scrape do pr√≥prio Prometheus (dentro da rede Docker)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']